/* wingpanel-panel.c generated by valac 0.14.1, the Vala compiler
 * generated from wingpanel-panel.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <libindicator/indicator-object.h>
#include <cairo.h>
#include <libindicator/indicator.h>
#include <libindicator/indicator-service.h>
#include <libindicator/indicator-service-manager.h>
#include <float.h>
#include <math.h>
#include <unique/uniqueapp.h>
#include <unique/uniqueenumtypes.h>
#include <glib/gi18n-lib.h>


#define WINGPANEL_TYPE_PANEL (wingpanel_panel_get_type ())
#define WINGPANEL_PANEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_TYPE_PANEL, WingpanelPanel))
#define WINGPANEL_PANEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_TYPE_PANEL, WingpanelPanelClass))
#define WINGPANEL_IS_PANEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_TYPE_PANEL))
#define WINGPANEL_IS_PANEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_TYPE_PANEL))
#define WINGPANEL_PANEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_TYPE_PANEL, WingpanelPanelClass))

typedef struct _WingpanelPanel WingpanelPanel;
typedef struct _WingpanelPanelClass WingpanelPanelClass;
typedef struct _WingpanelPanelPrivate WingpanelPanelPrivate;

#define WINGPANEL_TYPE_INDICATORS_MODEL (wingpanel_indicators_model_get_type ())
#define WINGPANEL_INDICATORS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_TYPE_INDICATORS_MODEL, WingpanelIndicatorsModel))
#define WINGPANEL_INDICATORS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_TYPE_INDICATORS_MODEL, WingpanelIndicatorsModelClass))
#define WINGPANEL_IS_INDICATORS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_TYPE_INDICATORS_MODEL))
#define WINGPANEL_IS_INDICATORS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_TYPE_INDICATORS_MODEL))
#define WINGPANEL_INDICATORS_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_TYPE_INDICATORS_MODEL, WingpanelIndicatorsModelClass))

typedef struct _WingpanelIndicatorsModel WingpanelIndicatorsModel;
typedef struct _WingpanelIndicatorsModelClass WingpanelIndicatorsModelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY (wingpanel_indicator_object_entry_get_type ())
#define WINGPANEL_INDICATOR_OBJECT_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY, WingpanelIndicatorObjectEntry))
#define WINGPANEL_INDICATOR_OBJECT_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY, WingpanelIndicatorObjectEntryClass))
#define WINGPANEL_IS_INDICATOR_OBJECT_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY))
#define WINGPANEL_IS_INDICATOR_OBJECT_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY))
#define WINGPANEL_INDICATOR_OBJECT_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY, WingpanelIndicatorObjectEntryClass))

typedef struct _WingpanelIndicatorObjectEntry WingpanelIndicatorObjectEntry;
typedef struct _WingpanelIndicatorObjectEntryClass WingpanelIndicatorObjectEntryClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block1Data Block1Data;
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))

struct _WingpanelPanel {
	GtkWindow parent_instance;
	WingpanelPanelPrivate * priv;
};

struct _WingpanelPanelClass {
	GtkWindowClass parent_class;
};

struct _WingpanelPanelPrivate {
	GtkMenuBar* menubar;
	WingpanelIndicatorsModel* model;
	GeeHashMap* menuhash;
};

struct _Block1Data {
	int _ref_count_;
	WingpanelPanel * self;
	cairo_t* context;
};


static gpointer wingpanel_panel_parent_class = NULL;

GType wingpanel_panel_get_type (void) G_GNUC_CONST;
GType wingpanel_indicators_model_get_type (void) G_GNUC_CONST;
#define WINGPANEL_PANEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), WINGPANEL_TYPE_PANEL, WingpanelPanelPrivate))
enum  {
	WINGPANEL_PANEL_DUMMY_PROPERTY
};
WingpanelPanel* wingpanel_panel_new (void);
WingpanelPanel* wingpanel_panel_construct (GType object_type);
WingpanelIndicatorsModel* wingpanel_indicators_model_get_default (void);
GeeArrayList* wingpanel_indicators_model_get_indicators (WingpanelIndicatorsModel* self);
void wingpanel_panel_load_indicator (WingpanelPanel* self, IndicatorObject* indicator);
static gboolean wingpanel_panel_draw_background (WingpanelPanel* self, GtkWidget* widget, cairo_t* context);
static gboolean _wingpanel_panel_draw_background_gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void wingpanel_panel_create_entry (WingpanelPanel* self, IndicatorObjectEntry* entry, IndicatorObject* object);
WingpanelIndicatorObjectEntry* wingpanel_indicator_object_entry_new (IndicatorObjectEntry* entry, IndicatorObject* iobject);
WingpanelIndicatorObjectEntry* wingpanel_indicator_object_entry_construct (GType object_type, IndicatorObjectEntry* entry, IndicatorObject* iobject);
GType wingpanel_indicator_object_entry_get_type (void) G_GNUC_CONST;
gchar* wingpanel_indicators_model_get_indicator_name (WingpanelIndicatorsModel* self, IndicatorObject* o);
static void wingpanel_panel_delete_entry (WingpanelPanel* self, IndicatorObjectEntry* entry, IndicatorObject* object);
static void wingpanel_panel_on_entry_added (WingpanelPanel* self, IndicatorObject* object, IndicatorObjectEntry* entry);
static void wingpanel_panel_on_entry_removed (WingpanelPanel* self, IndicatorObject* object, IndicatorObjectEntry* entry);
static void _wingpanel_panel_on_entry_added_indicator_object_entry_added (IndicatorObject* _sender, IndicatorObjectEntry* entry, gpointer self);
static void _wingpanel_panel_on_entry_removed_indicator_object_entry_removed (IndicatorObject* _sender, IndicatorObjectEntry* entry, gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (Block1Data* _data1_);
static void wingpanel_panel_rounded_bottom_left (WingpanelPanel* self, cairo_t* context, gdouble x, gdouble y, gdouble width, gdouble height, gdouble radius);
static void wingpanel_panel_rounded_bottom_right (WingpanelPanel* self, cairo_t* context, gdouble x, gdouble y, gdouble width, gdouble height, gdouble radius);
static void __lambda0_ (Block1Data* _data1_, GtkWidget* child);
static void ___lambda0__gtk_callback (GtkWidget* widget, gpointer self);
static void wingpanel_panel_rounded_bottom_left_stroke (WingpanelPanel* self, cairo_t* context, gdouble x, gdouble y, gdouble width, gdouble height, gdouble radius);
static void wingpanel_panel_rounded_bottom_right_stroke (WingpanelPanel* self, cairo_t* context, gdouble x, gdouble y, gdouble width, gdouble height, gdouble radius);
static gint wingpanel_panel_main (gchar** args, int args_length1);
static void wingpanel_panel_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean _wingpanel_panel_draw_background_gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self) {
	gboolean result;
	result = wingpanel_panel_draw_background (self, _sender, cr);
	return result;
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


WingpanelPanel* wingpanel_panel_construct (GType object_type) {
	WingpanelPanel * self = NULL;
	GeeHashMap* _tmp0_;
	GdkScreen* _tmp1_;
	GdkScreen* _tmp2_;
	GdkVisual* _tmp3_ = NULL;
	GtkMenuBar* _tmp4_;
	GtkMenuBar* _tmp5_;
	GtkMenuBar* _tmp6_;
	GtkMenuBar* _tmp7_;
	GtkMenuBar* _tmp8_;
	GtkMenuBar* _tmp9_;
	GtkMenuBar* _tmp10_;
	WingpanelIndicatorsModel* _tmp11_ = NULL;
	WingpanelIndicatorsModel* _tmp12_;
	GeeArrayList* _tmp13_ = NULL;
	GeeArrayList* indicators_list;
	GtkMenuBar* _tmp26_;
	self = (WingpanelPanel*) g_object_new (object_type, NULL);
	gtk_window_set_default_size ((GtkWindow*) self, -1, 25);
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, GTK_TYPE_MENU_ITEM, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->menuhash);
	self->priv->menuhash = _tmp0_;
	gtk_window_set_skip_taskbar_hint ((GtkWindow*) self, TRUE);
	gtk_window_set_decorated ((GtkWindow*) self, FALSE);
	gtk_widget_set_app_paintable ((GtkWidget*) self, TRUE);
	gtk_window_set_type_hint ((GtkWindow*) self, GDK_WINDOW_TYPE_HINT_DOCK);
	_tmp1_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp2_ = _tmp1_;
	_tmp3_ = gdk_screen_get_rgba_visual (_tmp2_);
	gtk_widget_set_visual ((GtkWidget*) self, _tmp3_);
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
	_tmp4_ = (GtkMenuBar*) gtk_menu_bar_new ();
	_tmp5_ = g_object_ref_sink (_tmp4_);
	_g_object_unref0 (self->priv->menubar);
	self->priv->menubar = _tmp5_;
	_tmp6_ = self->priv->menubar;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp6_);
	_tmp7_ = self->priv->menubar;
	g_object_set ((GtkWidget*) _tmp7_, "can-focus", TRUE, NULL);
	_tmp8_ = self->priv->menubar;
	gtk_container_set_border_width ((GtkContainer*) _tmp8_, (guint) 0);
	_tmp9_ = self->priv->menubar;
	gtk_widget_set_size_request ((GtkWidget*) _tmp9_, -1, 24);
	_tmp10_ = self->priv->menubar;
	gtk_buildable_set_name ((GtkBuildable*) _tmp10_, "indicator-applet-menubar");
	_tmp11_ = wingpanel_indicators_model_get_default ();
	_g_object_unref0 (self->priv->model);
	self->priv->model = _tmp11_;
	_tmp12_ = self->priv->model;
	_tmp13_ = wingpanel_indicators_model_get_indicators (_tmp12_);
	indicators_list = _tmp13_;
	{
		GeeArrayList* _tmp14_;
		GeeArrayList* _tmp15_;
		GeeArrayList* _o_list;
		GeeArrayList* _tmp16_;
		gint _tmp17_;
		gint _tmp18_;
		gint _o_size;
		gint _o_index;
		_tmp14_ = indicators_list;
		_tmp15_ = _g_object_ref0 (_tmp14_);
		_o_list = _tmp15_;
		_tmp16_ = _o_list;
		_tmp17_ = gee_collection_get_size ((GeeCollection*) _tmp16_);
		_tmp18_ = _tmp17_;
		_o_size = _tmp18_;
		_o_index = -1;
		while (TRUE) {
			gint _tmp19_;
			gint _tmp20_;
			gint _tmp21_;
			GeeArrayList* _tmp22_;
			gint _tmp23_;
			gpointer _tmp24_ = NULL;
			IndicatorObject* o;
			IndicatorObject* _tmp25_;
			_tmp19_ = _o_index;
			_o_index = _tmp19_ + 1;
			_tmp20_ = _o_index;
			_tmp21_ = _o_size;
			if (!(_tmp20_ < _tmp21_)) {
				break;
			}
			_tmp22_ = _o_list;
			_tmp23_ = _o_index;
			_tmp24_ = gee_abstract_list_get ((GeeAbstractList*) _tmp22_, _tmp23_);
			o = (IndicatorObject*) _tmp24_;
			_tmp25_ = o;
			wingpanel_panel_load_indicator (self, _tmp25_);
			_g_object_unref0 (o);
		}
		_g_object_unref0 (_o_list);
	}
	_tmp26_ = self->priv->menubar;
	g_signal_connect_object ((GtkWidget*) _tmp26_, "draw", (GCallback) _wingpanel_panel_draw_background_gtk_widget_draw, self, 0);
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	_g_object_unref0 (indicators_list);
	return self;
}


WingpanelPanel* wingpanel_panel_new (void) {
	return wingpanel_panel_construct (WINGPANEL_TYPE_PANEL);
}


static void wingpanel_panel_create_entry (WingpanelPanel* self, IndicatorObjectEntry* entry, IndicatorObject* object) {
	IndicatorObjectEntry* _tmp0_;
	IndicatorObject* _tmp1_;
	WingpanelIndicatorObjectEntry* _tmp2_;
	GtkMenuItem* _tmp3_;
	GtkMenuItem* menuitem;
	GeeHashMap* _tmp4_;
	WingpanelIndicatorsModel* _tmp5_;
	IndicatorObject* _tmp6_;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_;
	GtkMenuBar* _tmp9_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (entry != NULL);
	g_return_if_fail (object != NULL);
	_tmp0_ = entry;
	_tmp1_ = object;
	_tmp2_ = wingpanel_indicator_object_entry_new (_tmp0_, _tmp1_);
	_tmp3_ = (GtkMenuItem*) g_object_ref_sink (_tmp2_);
	menuitem = _tmp3_;
	_tmp4_ = self->priv->menuhash;
	_tmp5_ = self->priv->model;
	_tmp6_ = object;
	_tmp7_ = wingpanel_indicators_model_get_indicator_name (_tmp5_, _tmp6_);
	_tmp8_ = _tmp7_;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp4_, _tmp8_, menuitem);
	_g_free0 (_tmp8_);
	_tmp9_ = self->priv->menubar;
	gtk_menu_shell_prepend ((GtkMenuShell*) _tmp9_, (GtkWidget*) menuitem);
	_g_object_unref0 (menuitem);
}


static void wingpanel_panel_delete_entry (WingpanelPanel* self, IndicatorObjectEntry* entry, IndicatorObject* object) {
	WingpanelIndicatorsModel* _tmp0_;
	IndicatorObject* _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	GeeHashMap* _tmp8_;
	WingpanelIndicatorsModel* _tmp9_;
	IndicatorObject* _tmp10_;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_;
	gboolean _tmp13_ = FALSE;
	gboolean _tmp14_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (entry != NULL);
	g_return_if_fail (object != NULL);
	_tmp0_ = self->priv->model;
	_tmp1_ = object;
	_tmp2_ = wingpanel_indicators_model_get_indicator_name (_tmp0_, _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat ("\n\n", _tmp3_, NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat (_tmp5_, "\n\n", NULL);
	_tmp7_ = _tmp6_;
	g_print ("%s", _tmp7_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	_tmp8_ = self->priv->menuhash;
	_tmp9_ = self->priv->model;
	_tmp10_ = object;
	_tmp11_ = wingpanel_indicators_model_get_indicator_name (_tmp9_, _tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp8_, _tmp12_);
	_tmp14_ = _tmp13_;
	_g_free0 (_tmp12_);
	if (_tmp14_) {
		GeeHashMap* _tmp15_;
		WingpanelIndicatorsModel* _tmp16_;
		IndicatorObject* _tmp17_;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_;
		gpointer _tmp20_ = NULL;
		GtkMenuItem* _tmp21_;
		GtkMenuItem* menuitem;
		GtkMenuBar* _tmp22_;
		GtkMenuItem* _tmp23_;
		_tmp15_ = self->priv->menuhash;
		_tmp16_ = self->priv->model;
		_tmp17_ = object;
		_tmp18_ = wingpanel_indicators_model_get_indicator_name (_tmp16_, _tmp17_);
		_tmp19_ = _tmp18_;
		_tmp20_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp15_, _tmp19_);
		_tmp21_ = (GtkMenuItem*) _tmp20_;
		_g_free0 (_tmp19_);
		menuitem = _tmp21_;
		_tmp22_ = self->priv->menubar;
		_tmp23_ = menuitem;
		gtk_container_remove ((GtkContainer*) _tmp22_, (GtkWidget*) _tmp23_);
		_g_object_unref0 (menuitem);
	}
}


static void wingpanel_panel_on_entry_added (WingpanelPanel* self, IndicatorObject* object, IndicatorObjectEntry* entry) {
	IndicatorObjectEntry* _tmp0_;
	IndicatorObject* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (object != NULL);
	g_return_if_fail (entry != NULL);
	_tmp0_ = entry;
	_tmp1_ = object;
	wingpanel_panel_create_entry (self, _tmp0_, _tmp1_);
}


static void wingpanel_panel_on_entry_removed (WingpanelPanel* self, IndicatorObject* object, IndicatorObjectEntry* entry) {
	IndicatorObjectEntry* _tmp0_;
	IndicatorObject* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (object != NULL);
	g_return_if_fail (entry != NULL);
	_tmp0_ = entry;
	_tmp1_ = object;
	wingpanel_panel_delete_entry (self, _tmp0_, _tmp1_);
}


static void _wingpanel_panel_on_entry_added_indicator_object_entry_added (IndicatorObject* _sender, IndicatorObjectEntry* entry, gpointer self) {
	wingpanel_panel_on_entry_added (self, _sender, entry);
}


static void _wingpanel_panel_on_entry_removed_indicator_object_entry_removed (IndicatorObject* _sender, IndicatorObjectEntry* entry, gpointer self) {
	wingpanel_panel_on_entry_removed (self, _sender, entry);
}


void wingpanel_panel_load_indicator (WingpanelPanel* self, IndicatorObject* indicator) {
	IndicatorObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (indicator != NULL);
	_tmp0_ = indicator;
	if (INDICATOR_IS_OBJECT (_tmp0_)) {
		IndicatorObject* _tmp1_;
		IndicatorObject* _tmp2_;
		IndicatorObject* _tmp3_;
		IndicatorObject* _tmp4_;
		GList* _tmp5_ = NULL;
		GList* list;
		_tmp1_ = indicator;
		g_signal_connect_object (_tmp1_, "entry-added", (GCallback) _wingpanel_panel_on_entry_added_indicator_object_entry_added, self, 0);
		_tmp2_ = indicator;
		g_signal_connect_object (_tmp2_, "entry-removed", (GCallback) _wingpanel_panel_on_entry_removed_indicator_object_entry_removed, self, 0);
		_tmp3_ = indicator;
		g_object_ref ((GObject*) _tmp3_);
		_tmp4_ = indicator;
		_tmp5_ = indicator_object_get_entries (_tmp4_);
		list = _tmp5_;
		{
			gint i;
			i = 0;
			{
				gboolean _tmp6_;
				_tmp6_ = TRUE;
				while (TRUE) {
					gboolean _tmp7_;
					gint _tmp9_;
					GList* _tmp10_;
					guint _tmp11_ = 0U;
					GList* _tmp12_;
					gint _tmp13_;
					gconstpointer _tmp14_ = NULL;
					IndicatorObjectEntry* entry;
					IndicatorObjectEntry* _tmp15_;
					IndicatorObject* _tmp16_;
					_tmp7_ = _tmp6_;
					if (!_tmp7_) {
						gint _tmp8_;
						_tmp8_ = i;
						i = _tmp8_ + 1;
					}
					_tmp6_ = FALSE;
					_tmp9_ = i;
					_tmp10_ = list;
					_tmp11_ = g_list_length (_tmp10_);
					if (!(((guint) _tmp9_) < _tmp11_)) {
						break;
					}
					_tmp12_ = list;
					_tmp13_ = i;
					_tmp14_ = g_list_nth_data (_tmp12_, (guint) _tmp13_);
					entry = (IndicatorObjectEntry*) ((IndicatorObjectEntry*) _tmp14_);
					_tmp15_ = entry;
					_tmp16_ = indicator;
					wingpanel_panel_create_entry (self, _tmp15_, _tmp16_);
				}
			}
		}
	} else {
		WingpanelIndicatorsModel* _tmp17_;
		IndicatorObject* _tmp18_;
		gchar* _tmp19_ = NULL;
		gchar* _tmp20_;
		_tmp17_ = self->priv->model;
		_tmp18_ = indicator;
		_tmp19_ = wingpanel_indicators_model_get_indicator_name (_tmp17_, _tmp18_);
		_tmp20_ = _tmp19_;
		g_warning ("wingpanel-panel.vala:99: Unable to load %s\n", _tmp20_);
		_g_free0 (_tmp20_);
	}
}


static gpointer _cairo_reference0 (gpointer self) {
	return self ? cairo_reference (self) : NULL;
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (Block1Data* _data1_) {
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		_g_object_unref0 (_data1_->self);
		_cairo_destroy0 (_data1_->context);
		g_slice_free (Block1Data, _data1_);
	}
}


static void __lambda0_ (Block1Data* _data1_, GtkWidget* child) {
	WingpanelPanel * self;
	GtkWidget* _tmp0_;
	cairo_t* _tmp1_;
	cairo_t* _tmp2_;
	GtkWidget* _tmp3_;
	gint _tmp4_ = 0;
	self = _data1_->self;
	g_return_if_fail (child != NULL);
	_tmp0_ = child;
	_tmp1_ = _data1_->context;
	gtk_widget_draw (_tmp0_, _tmp1_);
	_tmp2_ = _data1_->context;
	_tmp3_ = child;
	_tmp4_ = gtk_widget_get_allocated_width (_tmp3_);
	cairo_translate (_tmp2_, (gdouble) _tmp4_, (gdouble) 0);
}


static void ___lambda0__gtk_callback (GtkWidget* widget, gpointer self) {
	__lambda0_ (self, widget);
}


static gboolean wingpanel_panel_draw_background (WingpanelPanel* self, GtkWidget* widget, cairo_t* context) {
	gboolean result = FALSE;
	Block1Data* _data1_;
	cairo_t* _tmp0_;
	cairo_t* _tmp1_;
	GdkRectangle monitor_dimensions = {0};
	GdkScreen* _tmp2_ = NULL;
	GdkRectangle _tmp3_ = {0};
	gint width = 0;
	gint natural = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	GtkWidget* _tmp6_;
	GtkTextDirection _tmp7_ = 0;
	gboolean right_align;
	gboolean _tmp8_;
	cairo_t* _tmp12_;
	cairo_t* _tmp13_;
	gint _tmp14_;
	cairo_t* _tmp15_;
	cairo_t* _tmp16_;
	gboolean _tmp17_;
	cairo_t* _tmp22_;
	cairo_t* _tmp23_;
	cairo_t* _tmp24_;
	cairo_t* _tmp25_;
	GtkWidget* _tmp26_;
	cairo_t* _tmp27_;
	GtkWidget* _tmp28_;
	gint _tmp29_ = 0;
	cairo_t* _tmp30_;
	cairo_t* _tmp31_;
	gboolean _tmp32_;
	cairo_t* _tmp37_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (widget != NULL, FALSE);
	g_return_val_if_fail (context != NULL, FALSE);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_tmp0_ = context;
	_tmp1_ = _cairo_reference0 (_tmp0_);
	_data1_->context = _tmp1_;
	_tmp2_ = gtk_window_get_screen ((GtkWindow*) self);
	gdk_screen_get_monitor_geometry (_tmp2_, 0, &_tmp3_);
	monitor_dimensions = _tmp3_;
	gtk_widget_get_preferred_width ((GtkWidget*) self, &_tmp4_, &_tmp5_);
	width = _tmp4_;
	natural = _tmp5_;
	_tmp6_ = widget;
	_tmp7_ = gtk_widget_get_direction (_tmp6_);
	right_align = _tmp7_ == GTK_TEXT_DIR_LTR;
	_tmp8_ = right_align;
	if (_tmp8_) {
		GdkRectangle _tmp9_;
		gint _tmp10_;
		gint _tmp11_;
		_tmp9_ = monitor_dimensions;
		_tmp10_ = _tmp9_.width;
		_tmp11_ = width;
		gtk_window_move ((GtkWindow*) self, _tmp10_ - _tmp11_, 0);
	} else {
		gtk_window_move ((GtkWindow*) self, 0, 0);
	}
	_tmp12_ = _data1_->context;
	cairo_set_operator (_tmp12_, CAIRO_OPERATOR_CLEAR);
	_tmp13_ = _data1_->context;
	_tmp14_ = width;
	cairo_rectangle (_tmp13_, 0.0, 0.0, (gdouble) _tmp14_, (gdouble) 25);
	_tmp15_ = _data1_->context;
	cairo_fill (_tmp15_);
	_tmp16_ = _data1_->context;
	cairo_set_operator (_tmp16_, CAIRO_OPERATOR_OVER);
	_tmp17_ = right_align;
	if (_tmp17_) {
		cairo_t* _tmp18_;
		gint _tmp19_;
		_tmp18_ = _data1_->context;
		_tmp19_ = width;
		wingpanel_panel_rounded_bottom_left (self, _tmp18_, (gdouble) 0, (gdouble) 0, (gdouble) _tmp19_, (gdouble) 25, (gdouble) 16);
	} else {
		cairo_t* _tmp20_;
		gint _tmp21_;
		_tmp20_ = _data1_->context;
		_tmp21_ = width;
		wingpanel_panel_rounded_bottom_right (self, _tmp20_, (gdouble) 0, (gdouble) 0, (gdouble) _tmp21_, (gdouble) 25, (gdouble) 16);
	}
	_tmp22_ = _data1_->context;
	cairo_clip (_tmp22_);
	_tmp23_ = _data1_->context;
	cairo_set_source_rgba (_tmp23_, 0.0, 0.0, 0.0, 0.9);
	_tmp24_ = _data1_->context;
	cairo_set_operator (_tmp24_, CAIRO_OPERATOR_OVER);
	_tmp25_ = _data1_->context;
	cairo_paint (_tmp25_);
	_tmp26_ = widget;
	gtk_container_foreach ((GtkContainer*) (GTK_IS_MENU_BAR (_tmp26_) ? ((GtkMenuBar*) _tmp26_) : NULL), ___lambda0__gtk_callback, _data1_);
	_tmp27_ = _data1_->context;
	_tmp28_ = widget;
	_tmp29_ = gtk_widget_get_allocated_width (_tmp28_);
	cairo_translate (_tmp27_, (gdouble) (-_tmp29_), (gdouble) 0);
	_tmp30_ = _data1_->context;
	cairo_set_source_rgba (_tmp30_, 1.0, 1.0, 1.0, 0.7);
	_tmp31_ = _data1_->context;
	cairo_set_operator (_tmp31_, CAIRO_OPERATOR_SOURCE);
	_tmp32_ = right_align;
	if (_tmp32_) {
		cairo_t* _tmp33_;
		gint _tmp34_;
		_tmp33_ = _data1_->context;
		_tmp34_ = width;
		wingpanel_panel_rounded_bottom_left_stroke (self, _tmp33_, (gdouble) 0, (gdouble) 0, (gdouble) _tmp34_, (gdouble) 25, (gdouble) 16);
	} else {
		cairo_t* _tmp35_;
		gint _tmp36_;
		_tmp35_ = _data1_->context;
		_tmp36_ = width;
		wingpanel_panel_rounded_bottom_right_stroke (self, _tmp35_, (gdouble) 0, (gdouble) 0, (gdouble) _tmp36_, (gdouble) 25, (gdouble) 16);
	}
	_tmp37_ = _data1_->context;
	cairo_stroke (_tmp37_);
	result = TRUE;
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return result;
}


static void wingpanel_panel_rounded_bottom_left (WingpanelPanel* self, cairo_t* context, gdouble x, gdouble y, gdouble width, gdouble height, gdouble radius) {
	cairo_t* _tmp0_;
	gdouble _tmp1_;
	gdouble _tmp2_;
	cairo_t* _tmp3_;
	gdouble _tmp4_;
	gdouble _tmp5_;
	gdouble _tmp6_;
	cairo_t* _tmp7_;
	gdouble _tmp8_;
	gdouble _tmp9_;
	gdouble _tmp10_;
	gdouble _tmp11_;
	cairo_t* _tmp12_;
	gdouble _tmp13_;
	gdouble _tmp14_;
	gdouble _tmp15_;
	gdouble _tmp16_;
	cairo_t* _tmp17_;
	gdouble _tmp18_;
	gdouble _tmp19_;
	gdouble _tmp20_;
	gdouble _tmp21_;
	gdouble _tmp22_;
	gdouble _tmp23_;
	gdouble _tmp24_;
	gdouble _tmp25_;
	gdouble _tmp26_;
	gdouble _tmp27_;
	cairo_t* _tmp28_;
	gdouble _tmp29_;
	gdouble _tmp30_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	_tmp0_ = context;
	_tmp1_ = x;
	_tmp2_ = y;
	cairo_move_to (_tmp0_, _tmp1_, _tmp2_);
	_tmp3_ = context;
	_tmp4_ = x;
	_tmp5_ = width;
	_tmp6_ = y;
	cairo_line_to (_tmp3_, _tmp4_ + _tmp5_, _tmp6_);
	_tmp7_ = context;
	_tmp8_ = x;
	_tmp9_ = width;
	_tmp10_ = y;
	_tmp11_ = height;
	cairo_line_to (_tmp7_, _tmp8_ + _tmp9_, _tmp10_ + _tmp11_);
	_tmp12_ = context;
	_tmp13_ = x;
	_tmp14_ = radius;
	_tmp15_ = y;
	_tmp16_ = height;
	cairo_line_to (_tmp12_, _tmp13_ + _tmp14_, _tmp15_ + _tmp16_);
	_tmp17_ = context;
	_tmp18_ = x;
	_tmp19_ = y;
	_tmp20_ = height;
	_tmp21_ = x;
	_tmp22_ = y;
	_tmp23_ = height;
	_tmp24_ = x;
	_tmp25_ = y;
	_tmp26_ = height;
	_tmp27_ = radius;
	cairo_curve_to (_tmp17_, _tmp18_, _tmp19_ + _tmp20_, _tmp21_, _tmp22_ + _tmp23_, _tmp24_, (_tmp25_ + _tmp26_) - _tmp27_);
	_tmp28_ = context;
	_tmp29_ = x;
	_tmp30_ = y;
	cairo_line_to (_tmp28_, _tmp29_, _tmp30_);
}


static void wingpanel_panel_rounded_bottom_left_stroke (WingpanelPanel* self, cairo_t* context, gdouble x, gdouble y, gdouble width, gdouble height, gdouble radius) {
	cairo_t* _tmp0_;
	gdouble _tmp1_;
	gdouble _tmp2_;
	gdouble _tmp3_;
	gdouble _tmp4_;
	cairo_t* _tmp5_;
	gdouble _tmp6_;
	gdouble _tmp7_;
	gdouble _tmp8_;
	gdouble _tmp9_;
	cairo_t* _tmp10_;
	gdouble _tmp11_;
	gdouble _tmp12_;
	gdouble _tmp13_;
	gdouble _tmp14_;
	gdouble _tmp15_;
	gdouble _tmp16_;
	gdouble _tmp17_;
	gdouble _tmp18_;
	gdouble _tmp19_;
	gdouble _tmp20_;
	cairo_t* _tmp21_;
	gdouble _tmp22_;
	gdouble _tmp23_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	_tmp0_ = context;
	_tmp1_ = x;
	_tmp2_ = width;
	_tmp3_ = y;
	_tmp4_ = height;
	cairo_move_to (_tmp0_, _tmp1_ + _tmp2_, _tmp3_ + _tmp4_);
	_tmp5_ = context;
	_tmp6_ = x;
	_tmp7_ = radius;
	_tmp8_ = y;
	_tmp9_ = height;
	cairo_line_to (_tmp5_, _tmp6_ + _tmp7_, _tmp8_ + _tmp9_);
	_tmp10_ = context;
	_tmp11_ = x;
	_tmp12_ = y;
	_tmp13_ = height;
	_tmp14_ = x;
	_tmp15_ = y;
	_tmp16_ = height;
	_tmp17_ = x;
	_tmp18_ = y;
	_tmp19_ = height;
	_tmp20_ = radius;
	cairo_curve_to (_tmp10_, _tmp11_, _tmp12_ + _tmp13_, _tmp14_, _tmp15_ + _tmp16_, _tmp17_, (_tmp18_ + _tmp19_) - _tmp20_);
	_tmp21_ = context;
	_tmp22_ = x;
	_tmp23_ = y;
	cairo_line_to (_tmp21_, _tmp22_, _tmp23_);
}


static void wingpanel_panel_rounded_bottom_right (WingpanelPanel* self, cairo_t* context, gdouble x, gdouble y, gdouble width, gdouble height, gdouble radius) {
	cairo_t* _tmp0_;
	gdouble _tmp1_;
	gdouble _tmp2_;
	cairo_t* _tmp3_;
	gdouble _tmp4_;
	gdouble _tmp5_;
	gdouble _tmp6_;
	cairo_t* _tmp7_;
	gdouble _tmp8_;
	gdouble _tmp9_;
	gdouble _tmp10_;
	gdouble _tmp11_;
	gdouble _tmp12_;
	cairo_t* _tmp13_;
	gdouble _tmp14_;
	gdouble _tmp15_;
	gdouble _tmp16_;
	gdouble _tmp17_;
	gdouble _tmp18_;
	gdouble _tmp19_;
	gdouble _tmp20_;
	gdouble _tmp21_;
	gdouble _tmp22_;
	gdouble _tmp23_;
	gdouble _tmp24_;
	gdouble _tmp25_;
	gdouble _tmp26_;
	cairo_t* _tmp27_;
	gdouble _tmp28_;
	gdouble _tmp29_;
	gdouble _tmp30_;
	cairo_t* _tmp31_;
	gdouble _tmp32_;
	gdouble _tmp33_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	_tmp0_ = context;
	_tmp1_ = x;
	_tmp2_ = y;
	cairo_move_to (_tmp0_, _tmp1_, _tmp2_);
	_tmp3_ = context;
	_tmp4_ = x;
	_tmp5_ = width;
	_tmp6_ = y;
	cairo_line_to (_tmp3_, _tmp4_ + _tmp5_, _tmp6_);
	_tmp7_ = context;
	_tmp8_ = x;
	_tmp9_ = width;
	_tmp10_ = y;
	_tmp11_ = height;
	_tmp12_ = radius;
	cairo_line_to (_tmp7_, _tmp8_ + _tmp9_, (_tmp10_ + _tmp11_) - _tmp12_);
	_tmp13_ = context;
	_tmp14_ = x;
	_tmp15_ = width;
	_tmp16_ = y;
	_tmp17_ = height;
	_tmp18_ = x;
	_tmp19_ = width;
	_tmp20_ = y;
	_tmp21_ = height;
	_tmp22_ = x;
	_tmp23_ = width;
	_tmp24_ = radius;
	_tmp25_ = y;
	_tmp26_ = height;
	cairo_curve_to (_tmp13_, _tmp14_ + _tmp15_, _tmp16_ + _tmp17_, _tmp18_ + _tmp19_, _tmp20_ + _tmp21_, (_tmp22_ + _tmp23_) - _tmp24_, _tmp25_ + _tmp26_);
	_tmp27_ = context;
	_tmp28_ = x;
	_tmp29_ = y;
	_tmp30_ = height;
	cairo_line_to (_tmp27_, _tmp28_, _tmp29_ + _tmp30_);
	_tmp31_ = context;
	_tmp32_ = x;
	_tmp33_ = y;
	cairo_line_to (_tmp31_, _tmp32_, _tmp33_);
}


static void wingpanel_panel_rounded_bottom_right_stroke (WingpanelPanel* self, cairo_t* context, gdouble x, gdouble y, gdouble width, gdouble height, gdouble radius) {
	cairo_t* _tmp0_;
	gdouble _tmp1_;
	gdouble _tmp2_;
	gdouble _tmp3_;
	cairo_t* _tmp4_;
	gdouble _tmp5_;
	gdouble _tmp6_;
	gdouble _tmp7_;
	gdouble _tmp8_;
	gdouble _tmp9_;
	cairo_t* _tmp10_;
	gdouble _tmp11_;
	gdouble _tmp12_;
	gdouble _tmp13_;
	gdouble _tmp14_;
	gdouble _tmp15_;
	gdouble _tmp16_;
	gdouble _tmp17_;
	gdouble _tmp18_;
	gdouble _tmp19_;
	gdouble _tmp20_;
	gdouble _tmp21_;
	gdouble _tmp22_;
	gdouble _tmp23_;
	cairo_t* _tmp24_;
	gdouble _tmp25_;
	gdouble _tmp26_;
	gdouble _tmp27_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	_tmp0_ = context;
	_tmp1_ = x;
	_tmp2_ = width;
	_tmp3_ = y;
	cairo_move_to (_tmp0_, _tmp1_ + _tmp2_, _tmp3_);
	_tmp4_ = context;
	_tmp5_ = x;
	_tmp6_ = width;
	_tmp7_ = y;
	_tmp8_ = height;
	_tmp9_ = radius;
	cairo_line_to (_tmp4_, _tmp5_ + _tmp6_, (_tmp7_ + _tmp8_) - _tmp9_);
	_tmp10_ = context;
	_tmp11_ = x;
	_tmp12_ = width;
	_tmp13_ = y;
	_tmp14_ = height;
	_tmp15_ = x;
	_tmp16_ = width;
	_tmp17_ = y;
	_tmp18_ = height;
	_tmp19_ = x;
	_tmp20_ = width;
	_tmp21_ = radius;
	_tmp22_ = y;
	_tmp23_ = height;
	cairo_curve_to (_tmp10_, _tmp11_ + _tmp12_, _tmp13_ + _tmp14_, _tmp15_ + _tmp16_, _tmp17_ + _tmp18_, (_tmp19_ + _tmp20_) - _tmp21_, _tmp22_ + _tmp23_);
	_tmp24_ = context;
	_tmp25_ = x;
	_tmp26_ = y;
	_tmp27_ = height;
	cairo_line_to (_tmp24_, _tmp25_, _tmp26_ + _tmp27_);
}


static gint wingpanel_panel_main (gchar** args, int args_length1) {
	gint result = 0;
	UniqueApp* _tmp0_;
	UniqueApp* app;
	UniqueApp* _tmp1_;
	gboolean _tmp2_ = FALSE;
	WingpanelPanel* _tmp7_;
	WingpanelPanel* _tmp8_;
	WingpanelPanel* panel;
	WingpanelPanel* _tmp9_;
	gtk_init (&args_length1, &args);
	_tmp0_ = unique_app_new ("org.elementary.Wingpanel", NULL);
	app = _tmp0_;
	_tmp1_ = app;
	_tmp2_ = unique_app_is_running (_tmp1_);
	if (_tmp2_) {
		UniqueApp* _tmp3_;
		UniqueResponse _tmp4_ = 0;
		UniqueResponse response;
		UniqueResponse _tmp5_;
		const gchar* _tmp6_ = NULL;
		_tmp3_ = app;
		_tmp4_ = unique_app_send_message (_tmp3_, (gint) UNIQUE_ACTIVATE, NULL);
		response = _tmp4_;
		_tmp5_ = response;
		if (_tmp5_ == UNIQUE_RESPONSE_OK) {
			result = 0;
			_g_object_unref0 (app);
			return result;
		}
		_tmp6_ = _ ("Failed to activate running instance");
		g_error ("wingpanel-panel.vala:211: %s", _tmp6_);
	}
	_tmp7_ = wingpanel_panel_new ();
	_tmp8_ = g_object_ref_sink (_tmp7_);
	panel = _tmp8_;
	_tmp9_ = panel;
	gtk_widget_show_all ((GtkWidget*) _tmp9_);
	gtk_main ();
	result = 0;
	_g_object_unref0 (panel);
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return wingpanel_panel_main (argv, argc);
}


static void wingpanel_panel_class_init (WingpanelPanelClass * klass) {
	wingpanel_panel_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (WingpanelPanelPrivate));
	G_OBJECT_CLASS (klass)->finalize = wingpanel_panel_finalize;
}


static void wingpanel_panel_instance_init (WingpanelPanel * self) {
	self->priv = WINGPANEL_PANEL_GET_PRIVATE (self);
}


static void wingpanel_panel_finalize (GObject* obj) {
	WingpanelPanel * self;
	self = WINGPANEL_PANEL (obj);
	_g_object_unref0 (self->priv->menubar);
	_g_object_unref0 (self->priv->model);
	_g_object_unref0 (self->priv->menuhash);
	G_OBJECT_CLASS (wingpanel_panel_parent_class)->finalize (obj);
}


GType wingpanel_panel_get_type (void) {
	static volatile gsize wingpanel_panel_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_panel_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelPanelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_panel_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelPanel), 0, (GInstanceInitFunc) wingpanel_panel_instance_init, NULL };
		GType wingpanel_panel_type_id;
		wingpanel_panel_type_id = g_type_register_static (GTK_TYPE_WINDOW, "WingpanelPanel", &g_define_type_info, 0);
		g_once_init_leave (&wingpanel_panel_type_id__volatile, wingpanel_panel_type_id);
	}
	return wingpanel_panel_type_id__volatile;
}



