/* wingpanel-indicator-file-model.c generated by valac 0.14.1, the Vala compiler
 * generated from wingpanel-indicator-file-model.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*- */
/*
 * Copyright (C) 2010 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by canonical.com
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <libindicator/indicator-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define WINGPANEL_TYPE_INDICATORS_MODEL (wingpanel_indicators_model_get_type ())
#define WINGPANEL_INDICATORS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_TYPE_INDICATORS_MODEL, WingpanelIndicatorsModel))
#define WINGPANEL_INDICATORS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_TYPE_INDICATORS_MODEL, WingpanelIndicatorsModelClass))
#define WINGPANEL_IS_INDICATORS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_TYPE_INDICATORS_MODEL))
#define WINGPANEL_IS_INDICATORS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_TYPE_INDICATORS_MODEL))
#define WINGPANEL_INDICATORS_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_TYPE_INDICATORS_MODEL, WingpanelIndicatorsModelClass))

typedef struct _WingpanelIndicatorsModel WingpanelIndicatorsModel;
typedef struct _WingpanelIndicatorsModelClass WingpanelIndicatorsModelClass;
typedef struct _WingpanelIndicatorsModelPrivate WingpanelIndicatorsModelPrivate;

#define WINGPANEL_TYPE_INDICATORS_FILE_MODEL (wingpanel_indicators_file_model_get_type ())
#define WINGPANEL_INDICATORS_FILE_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_TYPE_INDICATORS_FILE_MODEL, WingpanelIndicatorsFileModel))
#define WINGPANEL_INDICATORS_FILE_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_TYPE_INDICATORS_FILE_MODEL, WingpanelIndicatorsFileModelClass))
#define WINGPANEL_IS_INDICATORS_FILE_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_TYPE_INDICATORS_FILE_MODEL))
#define WINGPANEL_IS_INDICATORS_FILE_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_TYPE_INDICATORS_FILE_MODEL))
#define WINGPANEL_INDICATORS_FILE_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_TYPE_INDICATORS_FILE_MODEL, WingpanelIndicatorsFileModelClass))

typedef struct _WingpanelIndicatorsFileModel WingpanelIndicatorsFileModel;
typedef struct _WingpanelIndicatorsFileModelClass WingpanelIndicatorsFileModelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _WingpanelIndicatorsFileModelPrivate WingpanelIndicatorsFileModelPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _WingpanelIndicatorsModel {
	GObject parent_instance;
	WingpanelIndicatorsModelPrivate * priv;
};

struct _WingpanelIndicatorsModelClass {
	GObjectClass parent_class;
	GeeArrayList* (*get_indicators) (WingpanelIndicatorsModel* self);
	gchar* (*get_indicator_name) (WingpanelIndicatorsModel* self, IndicatorObject* o);
};

struct _WingpanelIndicatorsFileModel {
	WingpanelIndicatorsModel parent_instance;
	WingpanelIndicatorsFileModelPrivate * priv;
	GeeHashMap* indicator_map;
	GeeArrayList* indicator_list;
};

struct _WingpanelIndicatorsFileModelClass {
	WingpanelIndicatorsModelClass parent_class;
};


static gpointer wingpanel_indicators_model_parent_class = NULL;
static WingpanelIndicatorsModel* wingpanel_indicators_model__global_model;
static WingpanelIndicatorsModel* wingpanel_indicators_model__global_model = NULL;
static gpointer wingpanel_indicators_file_model_parent_class = NULL;
extern GeeHashMap* wingpanel_indicators_file_model_indicator_order;
GeeHashMap* wingpanel_indicators_file_model_indicator_order = NULL;

GType wingpanel_indicators_model_get_type (void) G_GNUC_CONST;
enum  {
	WINGPANEL_INDICATORS_MODEL_DUMMY_PROPERTY
};
WingpanelIndicatorsModel* wingpanel_indicators_model_get_default (void);
WingpanelIndicatorsFileModel* wingpanel_indicators_file_model_new (void);
WingpanelIndicatorsFileModel* wingpanel_indicators_file_model_construct (GType object_type);
GType wingpanel_indicators_file_model_get_type (void) G_GNUC_CONST;
void wingpanel_indicators_model_set_default (WingpanelIndicatorsModel* model);
GeeArrayList* wingpanel_indicators_model_get_indicators (WingpanelIndicatorsModel* self);
static GeeArrayList* wingpanel_indicators_model_real_get_indicators (WingpanelIndicatorsModel* self);
gchar* wingpanel_indicators_model_get_indicator_name (WingpanelIndicatorsModel* self, IndicatorObject* o);
static gchar* wingpanel_indicators_model_real_get_indicator_name (WingpanelIndicatorsModel* self, IndicatorObject* o);
WingpanelIndicatorsModel* wingpanel_indicators_model_construct (GType object_type);
static void wingpanel_indicators_model_finalize (GObject* obj);
enum  {
	WINGPANEL_INDICATORS_FILE_MODEL_DUMMY_PROPERTY
};
#define WINGPANEL_CONFIG_INDICATORDIR "/usr/lib/indicators3/"
gint wingpanel_indicators_file_model_indicator_sort_func (const gchar* a, const gchar* b);
static void wingpanel_indicators_file_model_load_indicator (WingpanelIndicatorsFileModel* self, const gchar* filename, const gchar* leaf);
static GeeArrayList* wingpanel_indicators_file_model_real_get_indicators (WingpanelIndicatorsModel* base);
static gchar* wingpanel_indicators_file_model_real_get_indicator_name (WingpanelIndicatorsModel* base, IndicatorObject* o);
static void wingpanel_indicators_file_model_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


WingpanelIndicatorsModel* wingpanel_indicators_model_get_default (void) {
	WingpanelIndicatorsModel* result = NULL;
	WingpanelIndicatorsModel* _tmp0_;
	WingpanelIndicatorsModel* _tmp2_;
	WingpanelIndicatorsModel* _tmp3_;
	_tmp0_ = wingpanel_indicators_model__global_model;
	if (_tmp0_ == NULL) {
		WingpanelIndicatorsFileModel* _tmp1_;
		_tmp1_ = wingpanel_indicators_file_model_new ();
		_g_object_unref0 (wingpanel_indicators_model__global_model);
		wingpanel_indicators_model__global_model = (WingpanelIndicatorsModel*) _tmp1_;
	}
	_tmp2_ = wingpanel_indicators_model__global_model;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


void wingpanel_indicators_model_set_default (WingpanelIndicatorsModel* model) {
	WingpanelIndicatorsModel* _tmp0_;
	WingpanelIndicatorsModel* _tmp1_;
	g_return_if_fail (model != NULL);
	_tmp0_ = model;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (wingpanel_indicators_model__global_model);
	wingpanel_indicators_model__global_model = _tmp1_;
}


static GeeArrayList* wingpanel_indicators_model_real_get_indicators (WingpanelIndicatorsModel* self) {
	g_critical ("Type `%s' does not implement abstract method `wingpanel_indicators_model_get_indicators'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return NULL;
}


GeeArrayList* wingpanel_indicators_model_get_indicators (WingpanelIndicatorsModel* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return WINGPANEL_INDICATORS_MODEL_GET_CLASS (self)->get_indicators (self);
}


static gchar* wingpanel_indicators_model_real_get_indicator_name (WingpanelIndicatorsModel* self, IndicatorObject* o) {
	g_critical ("Type `%s' does not implement abstract method `wingpanel_indicators_model_get_indicator_name'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return NULL;
}


gchar* wingpanel_indicators_model_get_indicator_name (WingpanelIndicatorsModel* self, IndicatorObject* o) {
	g_return_val_if_fail (self != NULL, NULL);
	return WINGPANEL_INDICATORS_MODEL_GET_CLASS (self)->get_indicator_name (self, o);
}


WingpanelIndicatorsModel* wingpanel_indicators_model_construct (GType object_type) {
	WingpanelIndicatorsModel * self = NULL;
	self = (WingpanelIndicatorsModel*) g_object_new (object_type, NULL);
	return self;
}


static void wingpanel_indicators_model_class_init (WingpanelIndicatorsModelClass * klass) {
	wingpanel_indicators_model_parent_class = g_type_class_peek_parent (klass);
	WINGPANEL_INDICATORS_MODEL_CLASS (klass)->get_indicators = wingpanel_indicators_model_real_get_indicators;
	WINGPANEL_INDICATORS_MODEL_CLASS (klass)->get_indicator_name = wingpanel_indicators_model_real_get_indicator_name;
	G_OBJECT_CLASS (klass)->finalize = wingpanel_indicators_model_finalize;
}


static void wingpanel_indicators_model_instance_init (WingpanelIndicatorsModel * self) {
}


static void wingpanel_indicators_model_finalize (GObject* obj) {
	WingpanelIndicatorsModel * self;
	self = WINGPANEL_INDICATORS_MODEL (obj);
	G_OBJECT_CLASS (wingpanel_indicators_model_parent_class)->finalize (obj);
}


GType wingpanel_indicators_model_get_type (void) {
	static volatile gsize wingpanel_indicators_model_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_indicators_model_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelIndicatorsModelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_indicators_model_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelIndicatorsModel), 0, (GInstanceInitFunc) wingpanel_indicators_model_instance_init, NULL };
		GType wingpanel_indicators_model_type_id;
		wingpanel_indicators_model_type_id = g_type_register_static (G_TYPE_OBJECT, "WingpanelIndicatorsModel", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&wingpanel_indicators_model_type_id__volatile, wingpanel_indicators_model_type_id);
	}
	return wingpanel_indicators_model_type_id__volatile;
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


WingpanelIndicatorsFileModel* wingpanel_indicators_file_model_construct (GType object_type) {
	WingpanelIndicatorsFileModel * self = NULL;
	gchar* skip_list = NULL;
	GeeHashMap* _tmp0_;
	GeeHashMap* _tmp1_;
	GeeArrayList* _tmp2_;
	GeeHashMap* _tmp3_;
	GeeHashMap* _tmp4_;
	GeeHashMap* _tmp5_;
	GeeHashMap* _tmp6_;
	GeeHashMap* _tmp7_;
	GeeHashMap* _tmp8_;
	GeeHashMap* _tmp9_;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_;
	const gchar* _tmp12_;
	const gchar* _tmp14_;
	const gchar* _tmp15_;
	gchar* _tmp16_;
	GeeArrayList* _tmp17_;
	GeeArrayList* versions;
	GeeArrayList* _tmp18_;
	GeeArrayList* _tmp19_;
	GeeArrayList* _tmp20_;
	GFile* dir;
	GFile* _tmp41_;
	GError * _inner_error_ = NULL;
	self = (WingpanelIndicatorsFileModel*) wingpanel_indicators_model_construct (object_type);
	_tmp0_ = gee_hash_map_new (G_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	_g_object_unref0 (self->indicator_map);
	self->indicator_map = _tmp0_;
	_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_INT, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (wingpanel_indicators_file_model_indicator_order);
	wingpanel_indicators_file_model_indicator_order = _tmp1_;
	_tmp2_ = gee_array_list_new (G_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
	_g_object_unref0 (self->indicator_list);
	self->indicator_list = _tmp2_;
	_tmp3_ = wingpanel_indicators_file_model_indicator_order;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp3_, "libapplication.so", GINT_TO_POINTER (7));
	_tmp4_ = wingpanel_indicators_file_model_indicator_order;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp4_, "libnetworkmenu.so", GINT_TO_POINTER (6));
	_tmp5_ = wingpanel_indicators_file_model_indicator_order;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp5_, "libsoundmenu.so", GINT_TO_POINTER (5));
	_tmp6_ = wingpanel_indicators_file_model_indicator_order;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp6_, "libmessaging.so", GINT_TO_POINTER (4));
	_tmp7_ = wingpanel_indicators_file_model_indicator_order;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp7_, "libme.so", GINT_TO_POINTER (3));
	_tmp8_ = wingpanel_indicators_file_model_indicator_order;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp8_, "libdatetime.so", GINT_TO_POINTER (2));
	_tmp9_ = wingpanel_indicators_file_model_indicator_order;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp9_, "libsession.so", GINT_TO_POINTER (1));
	_tmp10_ = g_getenv ("UNITY_PANEL_INDICATORS_SKIP");
	_tmp11_ = g_strdup (_tmp10_);
	_g_free0 (skip_list);
	skip_list = _tmp11_;
	_tmp12_ = skip_list;
	if (_tmp12_ == NULL) {
		gchar* _tmp13_;
		_tmp13_ = g_strdup ("");
		_g_free0 (skip_list);
		skip_list = _tmp13_;
	}
	_tmp14_ = skip_list;
	if (g_strcmp0 (_tmp14_, "all") == 0) {
		g_message ("wingpanel-indicator-file-model.vala:88: Skipping all indicator loading");
		_g_free0 (skip_list);
		return self;
	}
	_tmp15_ = skip_list;
	_tmp16_ = g_strconcat (_tmp15_, ",libappmenu.so", NULL);
	_g_free0 (skip_list);
	skip_list = _tmp16_;
	_tmp17_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL);
	versions = _tmp17_;
	_tmp18_ = versions;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp18_, "3");
	_tmp19_ = versions;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp19_, "4");
	_tmp20_ = versions;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp20_, "6");
	dir = NULL;
	{
		GeeArrayList* _tmp21_;
		GeeArrayList* _tmp22_;
		GeeArrayList* _version_list;
		GeeArrayList* _tmp23_;
		gint _tmp24_;
		gint _tmp25_;
		gint _version_size;
		gint _version_index;
		_tmp21_ = versions;
		_tmp22_ = _g_object_ref0 (_tmp21_);
		_version_list = _tmp22_;
		_tmp23_ = _version_list;
		_tmp24_ = gee_collection_get_size ((GeeCollection*) _tmp23_);
		_tmp25_ = _tmp24_;
		_version_size = _tmp25_;
		_version_index = -1;
		while (TRUE) {
			gint _tmp26_;
			gint _tmp27_;
			gint _tmp28_;
			GeeArrayList* _tmp29_;
			gint _tmp30_;
			gpointer _tmp31_ = NULL;
			gchar* version;
			GFile* _tmp32_ = NULL;
			GFile* _tmp33_;
			const gchar* _tmp34_;
			GFile* _tmp35_ = NULL;
			GFile* _tmp36_;
			GFile* version_path;
			GFile* _tmp37_;
			gboolean _tmp38_ = FALSE;
			_tmp26_ = _version_index;
			_version_index = _tmp26_ + 1;
			_tmp27_ = _version_index;
			_tmp28_ = _version_size;
			if (!(_tmp27_ < _tmp28_)) {
				break;
			}
			_tmp29_ = _version_list;
			_tmp30_ = _version_index;
			_tmp31_ = gee_abstract_list_get ((GeeAbstractList*) _tmp29_, _tmp30_);
			version = (gchar*) _tmp31_;
			_tmp32_ = g_file_new_for_path (WINGPANEL_CONFIG_INDICATORDIR);
			_tmp33_ = _tmp32_;
			_tmp34_ = version;
			_tmp35_ = g_file_get_child (_tmp33_, _tmp34_);
			_tmp36_ = _tmp35_;
			_g_object_unref0 (_tmp33_);
			version_path = _tmp36_;
			_tmp37_ = version_path;
			_tmp38_ = g_file_query_exists (_tmp37_, NULL);
			if (_tmp38_) {
				GFile* _tmp39_;
				GFile* _tmp40_;
				_tmp39_ = version_path;
				_tmp40_ = _g_object_ref0 (_tmp39_);
				_g_object_unref0 (dir);
				dir = _tmp40_;
				_g_object_unref0 (version_path);
				_g_free0 (version);
				break;
			}
			_g_object_unref0 (version_path);
			_g_free0 (version);
		}
		_g_object_unref0 (_version_list);
	}
	_tmp41_ = dir;
	if (_tmp41_ == NULL) {
		g_critical ("wingpanel-indicator-file-model.vala:119: No indicatordirectory found i" \
"n: %s. Check configuration.", WINGPANEL_CONFIG_INDICATORDIR);
		_g_object_unref0 (dir);
		_g_object_unref0 (versions);
		_g_free0 (skip_list);
		return self;
	}
	{
		GFile* _tmp42_;
		GFileEnumerator* _tmp43_ = NULL;
		GFileEnumerator* e;
		GeeArrayList* _tmp44_;
		GeeArrayList* sos;
		GFileInfo* file_info = NULL;
		GeeArrayList* _tmp61_;
		_tmp42_ = dir;
		_tmp43_ = g_file_enumerate_children (_tmp42_, G_FILE_ATTRIBUTE_STANDARD_NAME, 0, NULL, &_inner_error_);
		e = _tmp43_;
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		_tmp44_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL);
		sos = _tmp44_;
		while (TRUE) {
			GFileEnumerator* _tmp45_;
			GFileInfo* _tmp46_ = NULL;
			GFileInfo* _tmp47_;
			GFileInfo* _tmp48_;
			GFileInfo* _tmp49_;
			const gchar* _tmp50_ = NULL;
			gchar* _tmp51_;
			gchar* leaf;
			const gchar* _tmp52_;
			const gchar* _tmp53_;
			gboolean _tmp54_ = FALSE;
			const gchar* _tmp56_;
			gboolean _tmp57_ = FALSE;
			_tmp45_ = e;
			_tmp46_ = g_file_enumerator_next_file (_tmp45_, NULL, &_inner_error_);
			_tmp47_ = _tmp46_;
			if (_inner_error_ != NULL) {
				_g_object_unref0 (file_info);
				_g_object_unref0 (sos);
				_g_object_unref0 (e);
				goto __catch0_g_error;
			}
			_g_object_unref0 (file_info);
			file_info = _tmp47_;
			_tmp48_ = file_info;
			if (!(_tmp48_ != NULL)) {
				break;
			}
			_tmp49_ = file_info;
			_tmp50_ = g_file_info_get_name (_tmp49_);
			_tmp51_ = g_strdup (_tmp50_);
			leaf = _tmp51_;
			_tmp52_ = skip_list;
			_tmp53_ = leaf;
			_tmp54_ = string_contains (_tmp52_, _tmp53_);
			if (_tmp54_) {
				const gchar* _tmp55_;
				_tmp55_ = leaf;
				g_debug ("wingpanel-indicator-file-model.vala:136: SKIP LOADING: %s", _tmp55_);
				_g_free0 (leaf);
				continue;
			}
			_tmp56_ = leaf;
			_tmp57_ = g_str_has_suffix (_tmp56_, ".so");
			if (_tmp57_) {
				GeeArrayList* _tmp58_;
				const gchar* _tmp59_;
				const gchar* _tmp60_;
				_tmp58_ = sos;
				_tmp59_ = leaf;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp58_, _tmp59_);
				_tmp60_ = leaf;
				g_debug ("wingpanel-indicator-file-model.vala:143: LOADING: %s", _tmp60_);
			}
			_g_free0 (leaf);
		}
		_tmp61_ = sos;
		gee_list_sort ((GeeList*) _tmp61_, (GCompareFunc) wingpanel_indicators_file_model_indicator_sort_func);
		{
			GeeArrayList* _tmp62_;
			GeeArrayList* _tmp63_;
			GeeArrayList* _leaf_list;
			GeeArrayList* _tmp64_;
			gint _tmp65_;
			gint _tmp66_;
			gint _leaf_size;
			gint _leaf_index;
			_tmp62_ = sos;
			_tmp63_ = _g_object_ref0 (_tmp62_);
			_leaf_list = _tmp63_;
			_tmp64_ = _leaf_list;
			_tmp65_ = gee_collection_get_size ((GeeCollection*) _tmp64_);
			_tmp66_ = _tmp65_;
			_leaf_size = _tmp66_;
			_leaf_index = -1;
			while (TRUE) {
				gint _tmp67_;
				gint _tmp68_;
				gint _tmp69_;
				GeeArrayList* _tmp70_;
				gint _tmp71_;
				gpointer _tmp72_ = NULL;
				gchar* leaf;
				GFile* _tmp73_;
				gchar* _tmp74_ = NULL;
				gchar* _tmp75_;
				gchar* _tmp76_;
				gchar* _tmp77_;
				const gchar* _tmp78_;
				gchar* _tmp79_;
				gchar* _tmp80_;
				const gchar* _tmp81_;
				_tmp67_ = _leaf_index;
				_leaf_index = _tmp67_ + 1;
				_tmp68_ = _leaf_index;
				_tmp69_ = _leaf_size;
				if (!(_tmp68_ < _tmp69_)) {
					break;
				}
				_tmp70_ = _leaf_list;
				_tmp71_ = _leaf_index;
				_tmp72_ = gee_abstract_list_get ((GeeAbstractList*) _tmp70_, _tmp71_);
				leaf = (gchar*) _tmp72_;
				_tmp73_ = dir;
				_tmp74_ = g_file_get_path (_tmp73_);
				_tmp75_ = _tmp74_;
				_tmp76_ = g_strconcat (_tmp75_, "/", NULL);
				_tmp77_ = _tmp76_;
				_tmp78_ = leaf;
				_tmp79_ = g_strconcat (_tmp77_, _tmp78_, NULL);
				_tmp80_ = _tmp79_;
				_tmp81_ = leaf;
				wingpanel_indicators_file_model_load_indicator (self, _tmp80_, _tmp81_);
				_g_free0 (_tmp80_);
				_g_free0 (_tmp77_);
				_g_free0 (_tmp75_);
				_g_free0 (leaf);
			}
			_g_object_unref0 (_leaf_list);
		}
		_g_object_unref0 (file_info);
		_g_object_unref0 (sos);
		_g_object_unref0 (e);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* _error_ = NULL;
		GError* _tmp82_;
		const gchar* _tmp83_;
		_error_ = _inner_error_;
		_inner_error_ = NULL;
		_tmp82_ = _error_;
		_tmp83_ = _tmp82_->message;
		g_print ("Unable to read indicators: %s\n", _tmp83_);
		_g_error_free0 (_error_);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (dir);
		_g_object_unref0 (versions);
		_g_free0 (skip_list);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_g_object_unref0 (dir);
	_g_object_unref0 (versions);
	_g_free0 (skip_list);
	return self;
}


WingpanelIndicatorsFileModel* wingpanel_indicators_file_model_new (void) {
	return wingpanel_indicators_file_model_construct (WINGPANEL_TYPE_INDICATORS_FILE_MODEL);
}


gint wingpanel_indicators_file_model_indicator_sort_func (const gchar* a, const gchar* b) {
	gint result = 0;
	GeeHashMap* _tmp0_;
	const gchar* _tmp1_;
	gpointer _tmp2_ = NULL;
	GeeHashMap* _tmp3_;
	const gchar* _tmp4_;
	gpointer _tmp5_ = NULL;
	g_return_val_if_fail (a != NULL, 0);
	g_return_val_if_fail (b != NULL, 0);
	_tmp0_ = wingpanel_indicators_file_model_indicator_order;
	_tmp1_ = a;
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp1_);
	_tmp3_ = wingpanel_indicators_file_model_indicator_order;
	_tmp4_ = b;
	_tmp5_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp3_, _tmp4_);
	result = GPOINTER_TO_INT (_tmp2_) - GPOINTER_TO_INT (_tmp5_);
	return result;
}


static void wingpanel_indicators_file_model_load_indicator (WingpanelIndicatorsFileModel* self, const gchar* filename, const gchar* leaf) {
	IndicatorObject* o = NULL;
	const gchar* _tmp0_;
	IndicatorObject* _tmp1_;
	IndicatorObject* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (filename != NULL);
	g_return_if_fail (leaf != NULL);
	_tmp0_ = filename;
	_tmp1_ = indicator_object_new_from_file (_tmp0_);
	_g_object_unref0 (o);
	o = _tmp1_;
	_tmp2_ = o;
	if (INDICATOR_IS_OBJECT (_tmp2_)) {
		GeeHashMap* _tmp3_;
		IndicatorObject* _tmp4_;
		const gchar* _tmp5_;
		GeeArrayList* _tmp6_;
		IndicatorObject* _tmp7_;
		_tmp3_ = self->indicator_map;
		_tmp4_ = o;
		_tmp5_ = leaf;
		gee_abstract_map_set ((GeeAbstractMap*) _tmp3_, (GObject*) _tmp4_, _tmp5_);
		_tmp6_ = self->indicator_list;
		_tmp7_ = o;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp6_, (GObject*) _tmp7_);
	} else {
		const gchar* _tmp8_;
		_tmp8_ = filename;
		g_warning ("wingpanel-indicator-file-model.vala:179: Unable to load %s\n", _tmp8_);
	}
	_g_object_unref0 (o);
}


static GeeArrayList* wingpanel_indicators_file_model_real_get_indicators (WingpanelIndicatorsModel* base) {
	WingpanelIndicatorsFileModel * self;
	GeeArrayList* result = NULL;
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
	self = (WingpanelIndicatorsFileModel*) base;
	_tmp0_ = self->indicator_list;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


static gchar* wingpanel_indicators_file_model_real_get_indicator_name (WingpanelIndicatorsModel* base, IndicatorObject* o) {
	WingpanelIndicatorsFileModel * self;
	gchar* result = NULL;
	GeeHashMap* _tmp0_;
	IndicatorObject* _tmp1_;
	gpointer _tmp2_ = NULL;
	self = (WingpanelIndicatorsFileModel*) base;
	g_return_val_if_fail (o != NULL, NULL);
	_tmp0_ = self->indicator_map;
	_tmp1_ = o;
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, (GObject*) _tmp1_);
	result = (gchar*) _tmp2_;
	return result;
}


static void wingpanel_indicators_file_model_class_init (WingpanelIndicatorsFileModelClass * klass) {
	wingpanel_indicators_file_model_parent_class = g_type_class_peek_parent (klass);
	WINGPANEL_INDICATORS_MODEL_CLASS (klass)->get_indicators = wingpanel_indicators_file_model_real_get_indicators;
	WINGPANEL_INDICATORS_MODEL_CLASS (klass)->get_indicator_name = wingpanel_indicators_file_model_real_get_indicator_name;
	G_OBJECT_CLASS (klass)->finalize = wingpanel_indicators_file_model_finalize;
}


static void wingpanel_indicators_file_model_instance_init (WingpanelIndicatorsFileModel * self) {
}


static void wingpanel_indicators_file_model_finalize (GObject* obj) {
	WingpanelIndicatorsFileModel * self;
	self = WINGPANEL_INDICATORS_FILE_MODEL (obj);
	_g_object_unref0 (self->indicator_map);
	_g_object_unref0 (self->indicator_list);
	G_OBJECT_CLASS (wingpanel_indicators_file_model_parent_class)->finalize (obj);
}


GType wingpanel_indicators_file_model_get_type (void) {
	static volatile gsize wingpanel_indicators_file_model_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_indicators_file_model_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelIndicatorsFileModelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_indicators_file_model_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelIndicatorsFileModel), 0, (GInstanceInitFunc) wingpanel_indicators_file_model_instance_init, NULL };
		GType wingpanel_indicators_file_model_type_id;
		wingpanel_indicators_file_model_type_id = g_type_register_static (WINGPANEL_TYPE_INDICATORS_MODEL, "WingpanelIndicatorsFileModel", &g_define_type_info, 0);
		g_once_init_leave (&wingpanel_indicators_file_model_type_id__volatile, wingpanel_indicators_file_model_type_id);
	}
	return wingpanel_indicators_file_model_type_id__volatile;
}



