/* wingpanel-config.c generated by valac 0.14.1, the Vala compiler
 * generated from wingpanel-config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define WINGPANEL_CONFIG_INDICATORDIR "/usr/lib/indicators3/"



