/* wingpanel-object-entry.c generated by valac 0.14.1, the Vala compiler
 * generated from wingpanel-object-entry.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <libindicator/indicator-object.h>
#include <libindicator/indicator.h>
#include <libindicator/indicator-service.h>
#include <libindicator/indicator-service-manager.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>


#define WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY (wingpanel_indicator_object_entry_get_type ())
#define WINGPANEL_INDICATOR_OBJECT_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY, WingpanelIndicatorObjectEntry))
#define WINGPANEL_INDICATOR_OBJECT_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY, WingpanelIndicatorObjectEntryClass))
#define WINGPANEL_IS_INDICATOR_OBJECT_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY))
#define WINGPANEL_IS_INDICATOR_OBJECT_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY))
#define WINGPANEL_INDICATOR_OBJECT_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY, WingpanelIndicatorObjectEntryClass))

typedef struct _WingpanelIndicatorObjectEntry WingpanelIndicatorObjectEntry;
typedef struct _WingpanelIndicatorObjectEntryClass WingpanelIndicatorObjectEntryClass;
typedef struct _WingpanelIndicatorObjectEntryPrivate WingpanelIndicatorObjectEntryPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define WINGPANEL_TYPE_INDICATORS_MODEL (wingpanel_indicators_model_get_type ())
#define WINGPANEL_INDICATORS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_TYPE_INDICATORS_MODEL, WingpanelIndicatorsModel))
#define WINGPANEL_INDICATORS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_TYPE_INDICATORS_MODEL, WingpanelIndicatorsModelClass))
#define WINGPANEL_IS_INDICATORS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_TYPE_INDICATORS_MODEL))
#define WINGPANEL_IS_INDICATORS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_TYPE_INDICATORS_MODEL))
#define WINGPANEL_INDICATORS_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_TYPE_INDICATORS_MODEL, WingpanelIndicatorsModelClass))

typedef struct _WingpanelIndicatorsModel WingpanelIndicatorsModel;
typedef struct _WingpanelIndicatorsModelClass WingpanelIndicatorsModelClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _WingpanelIndicatorObjectEntry {
	GtkMenuItem parent_instance;
	WingpanelIndicatorObjectEntryPrivate * priv;
};

struct _WingpanelIndicatorObjectEntryClass {
	GtkMenuItemClass parent_class;
};

struct _WingpanelIndicatorObjectEntryPrivate {
	IndicatorObject* object;
};


static gpointer wingpanel_indicator_object_entry_parent_class = NULL;

GType wingpanel_indicator_object_entry_get_type (void) G_GNUC_CONST;
#define WINGPANEL_INDICATOR_OBJECT_ENTRY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY, WingpanelIndicatorObjectEntryPrivate))
enum  {
	WINGPANEL_INDICATOR_OBJECT_ENTRY_DUMMY_PROPERTY
};
WingpanelIndicatorObjectEntry* wingpanel_indicator_object_entry_new (IndicatorObjectEntry* entry, IndicatorObject* iobject);
WingpanelIndicatorObjectEntry* wingpanel_indicator_object_entry_construct (GType object_type, IndicatorObjectEntry* entry, IndicatorObject* iobject);
GType wingpanel_indicators_model_get_type (void) G_GNUC_CONST;
WingpanelIndicatorsModel* wingpanel_indicators_model_get_default (void);
gchar* wingpanel_indicators_model_get_indicator_name (WingpanelIndicatorsModel* self, IndicatorObject* o);
static gboolean wingpanel_indicator_object_entry_on_scroll_event (WingpanelIndicatorObjectEntry* self, GdkEventScroll* event);
static gboolean _wingpanel_indicator_object_entry_on_scroll_event_gtk_widget_scroll_event (GtkWidget* _sender, GdkEventScroll* event, gpointer self);
static void wingpanel_indicator_object_entry_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean _wingpanel_indicator_object_entry_on_scroll_event_gtk_widget_scroll_event (GtkWidget* _sender, GdkEventScroll* event, gpointer self) {
	gboolean result;
	result = wingpanel_indicator_object_entry_on_scroll_event (self, event);
	return result;
}


WingpanelIndicatorObjectEntry* wingpanel_indicator_object_entry_construct (GType object_type, IndicatorObjectEntry* entry, IndicatorObject* iobject) {
	WingpanelIndicatorObjectEntry * self = NULL;
	IndicatorObject* _tmp0_;
	IndicatorObject* _tmp1_;
	WingpanelIndicatorsModel* _tmp2_ = NULL;
	WingpanelIndicatorsModel* model;
	GtkHBox* _tmp3_;
	GtkHBox* _tmp4_;
	GtkHBox* box;
	GtkHBox* _tmp5_;
	gboolean _tmp6_ = FALSE;
	IndicatorObjectEntry* _tmp7_;
	GtkImage* _tmp8_;
	gboolean _tmp11_;
	gboolean _tmp19_ = FALSE;
	IndicatorObjectEntry* _tmp20_;
	GtkLabel* _tmp21_;
	gboolean _tmp24_;
	GtkHBox* _tmp37_;
	GtkHBox* _tmp38_;
	IndicatorObjectEntry* _tmp39_;
	GtkMenu* _tmp40_;
	g_return_val_if_fail (entry != NULL, NULL);
	g_return_val_if_fail (iobject != NULL, NULL);
	self = (WingpanelIndicatorObjectEntry*) g_object_new (object_type, NULL);
	_tmp0_ = iobject;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->object);
	self->priv->object = _tmp1_;
	_tmp2_ = wingpanel_indicators_model_get_default ();
	model = _tmp2_;
	_tmp3_ = (GtkHBox*) gtk_hbox_new (FALSE, 0);
	_tmp4_ = g_object_ref_sink (_tmp3_);
	box = _tmp4_;
	_tmp5_ = box;
	gtk_box_set_spacing ((GtkBox*) _tmp5_, 2);
	_tmp7_ = entry;
	_tmp8_ = _tmp7_->image;
	if (_tmp8_ != NULL) {
		IndicatorObjectEntry* _tmp9_;
		GtkImage* _tmp10_;
		_tmp9_ = entry;
		_tmp10_ = _tmp9_->image;
		_tmp6_ = GTK_IS_IMAGE (_tmp10_);
	} else {
		_tmp6_ = FALSE;
	}
	_tmp11_ = _tmp6_;
	if (_tmp11_) {
		WingpanelIndicatorsModel* _tmp12_;
		IndicatorObject* _tmp13_;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_;
		GtkHBox* _tmp16_;
		IndicatorObjectEntry* _tmp17_;
		GtkImage* _tmp18_;
		_tmp12_ = model;
		_tmp13_ = self->priv->object;
		_tmp14_ = wingpanel_indicators_model_get_indicator_name (_tmp12_, _tmp13_);
		_tmp15_ = _tmp14_;
		g_debug ("wingpanel-object-entry.vala:18: Indicator: %s has attribute image", _tmp15_);
		_g_free0 (_tmp15_);
		_tmp16_ = box;
		_tmp17_ = entry;
		_tmp18_ = _tmp17_->image;
		gtk_box_pack_start ((GtkBox*) _tmp16_, (GtkWidget*) _tmp18_, FALSE, FALSE, (guint) 0);
	}
	_tmp20_ = entry;
	_tmp21_ = _tmp20_->label;
	if (_tmp21_ != NULL) {
		IndicatorObjectEntry* _tmp22_;
		GtkLabel* _tmp23_;
		_tmp22_ = entry;
		_tmp23_ = _tmp22_->label;
		_tmp19_ = GTK_IS_LABEL (_tmp23_);
	} else {
		_tmp19_ = FALSE;
	}
	_tmp24_ = _tmp19_;
	if (_tmp24_) {
		WingpanelIndicatorsModel* _tmp25_;
		IndicatorObject* _tmp26_;
		gchar* _tmp27_ = NULL;
		gchar* _tmp28_;
		GdkColor color = {0};
		GdkColor _tmp29_;
		GdkColor _tmp30_ = {0};
		IndicatorObjectEntry* _tmp31_;
		GtkLabel* _tmp32_;
		GdkColor _tmp33_;
		GtkHBox* _tmp34_;
		IndicatorObjectEntry* _tmp35_;
		GtkLabel* _tmp36_;
		_tmp25_ = model;
		_tmp26_ = self->priv->object;
		_tmp27_ = wingpanel_indicators_model_get_indicator_name (_tmp25_, _tmp26_);
		_tmp28_ = _tmp27_;
		g_debug ("wingpanel-object-entry.vala:22: Indicator: %s has attribute label", _tmp28_);
		_g_free0 (_tmp28_);
		memset (&color, 0, sizeof (GdkColor));
		_tmp29_ = color;
		gdk_color_parse ("#ffffff", &_tmp30_);
		color = _tmp30_;
		_tmp31_ = entry;
		_tmp32_ = _tmp31_->label;
		_tmp33_ = color;
		gtk_widget_modify_fg ((GtkWidget*) _tmp32_, GTK_STATE_NORMAL, &_tmp33_);
		_tmp34_ = box;
		_tmp35_ = entry;
		_tmp36_ = _tmp35_->label;
		gtk_box_pack_end ((GtkBox*) _tmp34_, (GtkWidget*) _tmp36_, FALSE, FALSE, (guint) 0);
	}
	_tmp37_ = box;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp37_);
	_tmp38_ = box;
	gtk_widget_show ((GtkWidget*) _tmp38_);
	_tmp39_ = entry;
	_tmp40_ = _tmp39_->menu;
	if (_tmp40_ != NULL) {
		IndicatorObjectEntry* _tmp41_;
		GtkMenu* _tmp42_;
		_tmp41_ = entry;
		_tmp42_ = _tmp41_->menu;
		gtk_menu_item_set_submenu ((GtkMenuItem*) self, (GtkWidget*) _tmp42_);
	}
	gtk_widget_show ((GtkWidget*) self);
	g_signal_connect_object ((GtkWidget*) self, "scroll-event", (GCallback) _wingpanel_indicator_object_entry_on_scroll_event_gtk_widget_scroll_event, self, 0);
	_g_object_unref0 (box);
	_g_object_unref0 (model);
	return self;
}


WingpanelIndicatorObjectEntry* wingpanel_indicator_object_entry_new (IndicatorObjectEntry* entry, IndicatorObject* iobject) {
	return wingpanel_indicator_object_entry_construct (WINGPANEL_TYPE_INDICATOR_OBJECT_ENTRY, entry, iobject);
}


static gboolean wingpanel_indicator_object_entry_on_scroll_event (WingpanelIndicatorObjectEntry* self, GdkEventScroll* event) {
	gboolean result = FALSE;
	IndicatorObject* _tmp0_;
	GdkEventScroll _tmp1_;
	GdkScrollDirection _tmp2_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->priv->object;
	_tmp1_ = *event;
	_tmp2_ = _tmp1_.direction;
	g_signal_emit_by_name (_tmp0_, "scroll", 1, _tmp2_, NULL);
	result = FALSE;
	return result;
}


static void wingpanel_indicator_object_entry_class_init (WingpanelIndicatorObjectEntryClass * klass) {
	wingpanel_indicator_object_entry_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (WingpanelIndicatorObjectEntryPrivate));
	G_OBJECT_CLASS (klass)->finalize = wingpanel_indicator_object_entry_finalize;
}


static void wingpanel_indicator_object_entry_instance_init (WingpanelIndicatorObjectEntry * self) {
	self->priv = WINGPANEL_INDICATOR_OBJECT_ENTRY_GET_PRIVATE (self);
}


static void wingpanel_indicator_object_entry_finalize (GObject* obj) {
	WingpanelIndicatorObjectEntry * self;
	self = WINGPANEL_INDICATOR_OBJECT_ENTRY (obj);
	_g_object_unref0 (self->priv->object);
	G_OBJECT_CLASS (wingpanel_indicator_object_entry_parent_class)->finalize (obj);
}


GType wingpanel_indicator_object_entry_get_type (void) {
	static volatile gsize wingpanel_indicator_object_entry_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_indicator_object_entry_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelIndicatorObjectEntryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_indicator_object_entry_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelIndicatorObjectEntry), 0, (GInstanceInitFunc) wingpanel_indicator_object_entry_instance_init, NULL };
		GType wingpanel_indicator_object_entry_type_id;
		wingpanel_indicator_object_entry_type_id = g_type_register_static (GTK_TYPE_MENU_ITEM, "WingpanelIndicatorObjectEntry", &g_define_type_info, 0);
		g_once_init_leave (&wingpanel_indicator_object_entry_type_id__volatile, wingpanel_indicator_object_entry_type_id);
	}
	return wingpanel_indicator_object_entry_type_id__volatile;
}



